services:
  cert-manager:
    build: .
    container_name: letsencrypt-panel
    env_file:
      - .env
    ports:
      - "8484:8080"
    volumes:
      - ./data:/app/data
      - ./credentials:/app/credentials
      - ./certs/letsencrypt:/etc/letsencrypt
      - ./certs/work:/var/lib/letsencrypt
      - ./certs/log:/var/log/letsencrypt
    restart: unless-stopped
